package main

func main() {

	//Receiver 	Value
	//(t T)		T and *T
	//(t *T)	*T
	//NON-POINTER RECEIVER & NON-POINTER VALUE
	//NON-POINTER RECEIVER & POINTER VALUE
	//POINTER RECEIVER & POINTER VALUE
	//POINTER RECEIVER & NON-POINTER VALUE
}
